# Data Processing with Numpy, Pandas, R, Matplotlib and TensorBoard

---
In this chapter, we review some common libraries for helping with data processing and visualization. 

In [ ]:
!pip install numpy jax jaxlib

## Numpy 

In [ ]:
import numpy as np

There are many ways to create numpy arrays.

In [ ]:
array1 = np.array([[1,2,3],[4,5,6]])
print(array1)

[[1 2 3]
 [4 5 6]]


In [ ]:
array2 = np.random.randn(10, 2)
print(array2)

[[-1.56793743  0.6366604 ]
 [ 0.59910695 -0.01405223]
 [-0.61263424  1.23294479]
 [ 0.95040163  1.4802104 ]
 [ 0.09063192 -0.15759336]
 [ 0.33215053  1.65622958]
 [ 1.26707061 -1.27484765]
 [-0.29766302 -1.02118591]
 [ 0.0320943  -0.20166682]
 [-0.49850528  0.9487797 ]]


In [ ]:
array3 = np.arange(15).reshape(3, 5)
print(array3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
identity_array = np.identity(10,dtype=np.float32)
print(identity_array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
zero_array = np.zeros((10, 3), dtype=np.float32)
print(zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
one_array = np.ones((10, 3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
similar = np.ones_like(identity_array)
print(similar)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


More array creation routines can be found [here](https://numpy.org/devdocs/reference/routines.array-creation.html).

## Array Indexing and Reshaping

The default behavior for array indexing is the same as python slicing. 

In [ ]:
array = np.random.randn(100, 10,15,10)

In [ ]:
print(array[:, 0, 0, 0])

In [ ]:
print(array[:, :, 0, 0])

NameError: ignored

In [ ]:
print(array[0:10, :, 0, 0])

In [ ]:
print(array[0:10:3, 0, 0, 0])

[ 1.70739505  1.18935766  0.78795478 -0.71567064]


In [ ]:
print(array[:-2, 0, 0, 0])

[ 1.70739505 -0.82967023 -0.47806151  1.18935766 -0.19409658  3.48876395
  0.78795478 -0.11744069  0.18225104 -0.71567064  0.52469674 -1.28110106
  0.23100205  0.34824142  2.17574744 -1.37879631  2.09442301 -0.96574986
 -1.16384336  0.03326084 -0.30041156 -0.37534001  0.5521689   1.0167317
  0.58456116 -2.19289576  0.08047507  0.40349151  0.02784855 -0.11269567
 -1.31467281  0.32141509  0.11114926  0.91552911  0.19134159 -0.41566672
  0.45062059  0.22561221  0.58307745 -0.53180078  0.82262677  0.69916903
 -0.30527753  1.0929337  -0.41442585  0.11077776 -0.65790374 -0.48550589
  0.29224714  0.79403733 -1.02997915  0.8964799  -0.24323762 -0.39795815
 -0.08449417 -0.81057055 -1.24803236  0.49490515  0.47805969  1.44003969
 -1.31886762  0.9069199  -1.51054788 -2.09495386  0.5742426   0.60152976
 -1.57569774  0.3122826  -0.60205861  0.85670391  0.02309827  2.56951119
  2.26961415  1.6612367  -0.45859023  1.35893445  0.2773309  -0.27660397
 -0.17536644  0.23391327 -0.58150561 -1.22580243  0.

**Pay** attention to the following code! Slicing does not create a copy!

In [ ]:
x = np.random.randn(10,10)
print(x)

[[ 0.76427026  0.88775403  3.45553424  0.03308661 -0.75142953 -0.46277806
   0.00966027  1.10242286  0.58688732 -0.54551312]
 [ 0.80304288  1.05363774 -2.06971814 -0.19376588  0.57991499 -0.31954218
  -0.99928138 -0.44789182 -0.69495066 -1.28872901]
 [-0.53787696 -0.09445237  1.52104535  0.0822447   1.18106685  0.15607149
  -0.6821166  -1.51457795  0.15448911  0.42905676]
 [ 0.56669671 -2.21142941 -0.04274403 -0.96957616 -0.41505699 -0.86983893
   1.50518868  0.97805588 -1.47067023 -0.10977444]
 [ 0.82665705  0.74811137  0.60961714 -0.1340682  -0.31217379 -1.22174085
   0.23137816  0.10118349  0.03219998 -1.66568723]
 [ 1.81067336 -0.20512699  0.5607943   1.04742779 -0.84251799 -0.92911075
  -2.0960608  -0.52416447 -1.70485393 -1.07688149]
 [-1.02749612  0.13534936  1.43340725 -0.05720198  1.26419631  0.58344737
  -0.82710977  0.52730983 -0.06526653  1.01148901]
 [-1.16610828 -0.22437768  0.07896258  0.0956287  -2.39667175 -1.21767117
  -0.34859794  0.4032185   0.94626212  0.7094242 ]


In [ ]:
y = x[:, 0]
y[:]=1
print(x) # x is changed as well

[[ 1.          0.88775403  3.45553424  0.03308661 -0.75142953 -0.46277806
   0.00966027  1.10242286  0.58688732 -0.54551312]
 [ 1.          1.05363774 -2.06971814 -0.19376588  0.57991499 -0.31954218
  -0.99928138 -0.44789182 -0.69495066 -1.28872901]
 [ 1.         -0.09445237  1.52104535  0.0822447   1.18106685  0.15607149
  -0.6821166  -1.51457795  0.15448911  0.42905676]
 [ 1.         -2.21142941 -0.04274403 -0.96957616 -0.41505699 -0.86983893
   1.50518868  0.97805588 -1.47067023 -0.10977444]
 [ 1.          0.74811137  0.60961714 -0.1340682  -0.31217379 -1.22174085
   0.23137816  0.10118349  0.03219998 -1.66568723]
 [ 1.         -0.20512699  0.5607943   1.04742779 -0.84251799 -0.92911075
  -2.0960608  -0.52416447 -1.70485393 -1.07688149]
 [ 1.          0.13534936  1.43340725 -0.05720198  1.26419631  0.58344737
  -0.82710977  0.52730983 -0.06526653  1.01148901]
 [ 1.         -0.22437768  0.07896258  0.0956287  -2.39667175 -1.21767117
  -0.34859794  0.4032185   0.94626212  0.7094242 ]


To prevent unwanted reference, use `copy` methods instead. 

Note that this will be a common pattern!

In [ ]:
z = x[0,:].copy()

In [ ]:
z[:]=10 # Nothing should change
print(x)

[[ 1.          0.88775403  3.45553424  0.03308661 -0.75142953 -0.46277806
   0.00966027  1.10242286  0.58688732 -0.54551312]
 [ 1.          1.05363774 -2.06971814 -0.19376588  0.57991499 -0.31954218
  -0.99928138 -0.44789182 -0.69495066 -1.28872901]
 [ 1.         -0.09445237  1.52104535  0.0822447   1.18106685  0.15607149
  -0.6821166  -1.51457795  0.15448911  0.42905676]
 [ 1.         -2.21142941 -0.04274403 -0.96957616 -0.41505699 -0.86983893
   1.50518868  0.97805588 -1.47067023 -0.10977444]
 [ 1.          0.74811137  0.60961714 -0.1340682  -0.31217379 -1.22174085
   0.23137816  0.10118349  0.03219998 -1.66568723]
 [ 1.         -0.20512699  0.5607943   1.04742779 -0.84251799 -0.92911075
  -2.0960608  -0.52416447 -1.70485393 -1.07688149]
 [ 1.          0.13534936  1.43340725 -0.05720198  1.26419631  0.58344737
  -0.82710977  0.52730983 -0.06526653  1.01148901]
 [ 1.         -0.22437768  0.07896258  0.0956287  -2.39667175 -1.21767117
  -0.34859794  0.4032185   0.94626212  0.7094242 ]


*In* addition, one can also index the array using *boolean conditions*. We leave these tasks to pandas. 

Here we demonstrate how to change the shape of tensors. This is a very common approach in building neural networks. 

In [ ]:
x = np.random.randn(10, 5)
print(x[:, None, :].shape) # This will add a new dimension

(10, 1, 5)


In [ ]:
print(np.expand_dims(x, 1).shape) # Doing this has the same effect

(10, 1, 5)


In [ ]:
x = x[:, None, :]
print(x.squeeze().shape) # Doing this removes the 'extra' dimension

(10, 5)


Note that `x.reshape(...)` behaves as one would expect. However, in situations when the dimensionality of a tensor is high, it can lead to quite some confusion. Thus we introduce *einops* package (see [here](https://github.com/arogozhnikov/einops)). 

In [ ]:
!pip install einops

In [ ]:
from einops import rearrange, repeat, reduce


In [ ]:
x = np.random.randn(10,4, 2, 2)
rearrange(x, 'b h j k -> b h (j k)').shape

(10, 4, 4)

In [ ]:
rearrange(x, 'b h j k -> b j h k').shape

(10, 2, 4, 2)

In [ ]:
rearrange(x, '(b1 b2) h j k ->b1 b2 (j k) h', b1=2).shape

(2, 5, 4, 4)

In [ ]:
reduce(x, 'b h j k -> b h j', 'sum').shape

(10, 4, 2)

In [ ]:
reduce(x, 'b (h1 h2) j k -> b h2 j k', 'max', h1=2).shape

(10, 2, 2, 2)

## Broadcast and Eimsum

The following contents are some of the most difficult (but very essential) for building neural networks. Let us start with a simple example. 

### Broadcast

Essentially, broadcast is a mechanism to avoid writing repeat. 

In [ ]:
x = np.random.randn(10)
y = np.random.randn(4)


In [ ]:
x*y # This will not work

ValueError: ignored

In [ ]:
x[:, None]*y # This works however

array([[ 2.69246473e-01,  6.07397378e-02,  8.12123759e-02,
         1.32630564e-01],
       [ 1.35745153e+00,  3.06229639e-01,  4.09445898e-01,
         6.68679371e-01],
       [-2.72986938e-02, -6.15835553e-03, -8.23406064e-03,
        -1.34473114e-02],
       [-3.24840978e+00, -7.32813901e-01, -9.79812560e-01,
        -1.60016366e+00],
       [ 8.09465047e-01,  1.82608501e-01,  2.44157626e-01,
         3.98741735e-01],
       [-4.65325355e+00, -1.04973483e+00, -1.40355330e+00,
        -2.29218840e+00],
       [ 1.97093058e-02,  4.44625347e-03,  5.94488586e-03,
         9.70878583e-03],
       [ 9.47906482e-01,  2.13839723e-01,  2.85915491e-01,
         4.66937858e-01],
       [-1.84567782e+00, -4.16369380e-01, -5.56708800e-01,
        -9.09179190e-01],
       [-1.31921557e+00, -2.97603927e-01, -3.97912847e-01,
        -6.49844372e-01]])

What happens under the hood. 

`x[: None]` -> $10 \times 1$

`y` -> $4$

During the operation, `x[:, None]` becomes $10 \times 4$ while `y` becomes $10 \times 4$. This is achieved by replicating `x` 4 times in the second dimension, and by replicating `y` 10 times in the first dimension. 

In general, to read brandcast, read from the trailing dimension (last 1). For example, let us say we have 

$4 \times 2 \times 1 \times 5$ and $1 \times 3 \times 5$. They are actually broadcastable. To determine whether this is possible, first check the one that dimensionatliy. In the second case, it is 3 and the first is 4, therefore add a 1 in the beginning. Therefore the dimensionality of the second element becomes $1 \times 1 \times 3 \times 5$. Now, for each corresponding dimension, if one is $1$ and the other is not, then replicate the tensor on that dimension.  

Many operations support broadcast. Most element-wise operations can be easily understood. However, the @ operation deserves some explanation . 

In [ ]:
 x = np.random.randn(64, 10, 5)
 y = np.random.randn(5, 10)
 (x @ y).shape # This works. 

(64, 10, 10)

In [ ]:
(y @ x).shape # This also works. 

(64, 5, 5)

In [ ]:
x = np.random.randn(100, 10, 5)
y = np.random.randn(5)
(x @ y).shape # What happens here?

(100, 10)

In [ ]:
|(x @ y[:, None]).shape # What happens here again? 

SyntaxError: ignored

In [ ]:
x = np.random.randn(10, 3, 3)
y = np.random.randn(10, 3)

(x @ y).shape # This will not work

ValueError: ignored

In [ ]:
x = np.random.randn(10, 3, 3)
y = np.random.randn(10, 3, 1)
(x @ y).shape # This will work, though

SyntaxError: ignored

Basically, to understand how @ operator behaves, check again from the trailing dimension, and see whether normal matrix munipulation can be used. Then, apply the broadcast rule. 

### Einsum

A simple mechanism invented by Einstein. The code looks like `np.einsum('ijk, jkh -> ijh', x, y)`. To read this, following the following steps.

1. Understanding the dimensionality of the input and output.
2. Write out the existing dimensions.
3. Sum over the 'missing' dimensions. 

For the example above, call the result $z$, then we have.

1. $x$ is $I \times J \times K$, $y$ is $J \times K \times H$ and $z$ is $I \times J \times H$. 
2. To work out the expression, we have $z_{ijh} = ? x_{ij\cdot} y_{j\cdot h}.$
3. Now since $k$ is missing from the r.h.s., we must have it in the sum. In other words $z_{ijh} = \sum_{k=1}^K x_{ijk} y_{jkh}$. 

In [ ]:
I, J, K, H = 10, 15, 20, 25
x = np.random.randn(I, J, K)
y = np.random.randn(J, K, H)
z = np.einsum('ijk, jkh -> ijh', x, y)
print(z)

[[[ 4.03750527e+00 -9.68197881e-01  1.10772439e+00 ...  1.61086675e+00
   -1.83344758e+00  4.13492296e+00]
  [ 2.28206905e+00  1.92387429e-01 -3.77681138e+00 ...  9.87125380e+00
   -9.42294677e-01  6.98349977e+00]
  [ 4.12193311e+00  6.24722270e+00 -8.66758394e+00 ...  4.24405915e+00
   -4.14486624e+00 -8.15531166e+00]
  ...
  [ 1.55890407e+00  5.32265788e-01 -4.05868463e-01 ... -2.72659331e+00
   -6.43122550e+00  1.09159200e+01]
  [-1.07177325e+00 -1.79211183e-01 -2.91232536e+00 ...  2.66177604e+00
   -5.87059927e-01  3.47696347e-02]
  [ 8.21178365e+00 -3.07423838e-01 -5.42349636e+00 ...  4.14775122e-01
   -2.76719955e-01  7.71236636e+00]]

 [[ 5.12333913e+00 -5.39663002e+00  2.97559138e+00 ...  4.62566613e+00
   -5.91984088e+00  2.58990859e+00]
  [ 4.47115403e+00  6.03989335e+00  8.83710477e-01 ... -2.93069296e+00
    6.62988066e+00  1.76698830e+00]
  [-7.81021180e-03  1.78641838e+00  4.08770929e+00 ...  6.82469007e+00
    5.19621130e-01  8.47721876e-01]
  ...
  [-1.44610883e+00  2.6

Exercises: Write out the formula for the following expression

In [ ]:
I, J, K, H = 10, 15, 20, 25
x = np.random.randn(I, J, K)
y = np.random.randn(J, K, H)
z = np.einsum('ijk, jkh -> ijh', x, y)
print(z)

[[[ 1.32850414e+01 -1.17862221e+01 -3.88376991e+00 ...  2.64225490e+00
    3.87969992e+00  4.30443416e+00]
  [ 5.13668017e+00  3.23763161e+00  7.24910533e+00 ... -2.56560776e+00
    4.18483312e-01 -7.15421954e+00]
  [-4.07819692e-01 -6.81364503e+00  2.56629978e+00 ...  3.30268401e+00
   -1.65480933e+00  3.17196172e+00]
  ...
  [-7.91667776e+00  5.30470785e+00 -3.13740156e+00 ... -5.01466700e+00
   -2.87450039e+00 -7.57635525e+00]
  [ 5.78434049e+00  9.85758951e-01 -5.47683363e+00 ... -4.10746900e+00
    7.60243979e-01 -4.90718653e+00]
  [ 1.97183282e+00 -5.67528267e+00 -8.34524629e+00 ...  1.32441630e+00
    1.58631304e+00  1.51526813e+00]]

 [[ 1.29951254e-02  4.54326264e-01 -5.06113409e+00 ...  8.26285146e-01
    2.50351583e+00  2.03509988e+00]
  [-5.09982818e-01  4.00567971e+00  4.10698958e+00 ... -3.93500229e+00
    6.67625148e+00 -6.43372950e+00]
  [ 3.68632031e+00 -5.88524012e+00  1.62574519e+00 ...  6.54119567e-01
    4.09069480e+00 -5.70359653e+00]
  ...
  [-7.84700642e+00  4.2

### Below are applications of einsums

In [ ]:
np.einsum("ii -> i", np.random.randn(3,3)) # Diagonal

array([ 0.30539357,  0.31014698, -1.01143002])

In [ ]:
x = np.random.randn(5)
y = np.random.randn(4)
np.einsum('i,j -> ij', x, y) # Outer product

array([[ 1.51928611e+00,  1.93022433e-01, -2.07303396e-02,
        -1.49958455e-01],
       [-1.41154355e+00, -1.79333944e-01,  1.92602150e-02,
         1.39323916e-01],
       [ 1.19202626e+00,  1.51444687e-01, -1.62649478e-02,
        -1.17656849e-01],
       [ 5.58495255e+00,  7.09557683e-01, -7.62055036e-02,
        -5.51252888e-01],
       [-2.25903588e-01, -2.87006246e-02,  3.08240698e-03,
         2.22974151e-02]])

In [ ]:
x = np.random.randn(15,2,3)
y = np.random.randn(15,3,15)
np.einsum('bij, bjk -> bik', x, y) # Batched Matrix Products

array([[[ 3.58765477e-02,  1.83282007e+00,  1.90022864e+00,
          9.96048950e-01,  8.87712280e-01, -1.89307486e-01,
         -1.20374298e+00,  1.72468309e+00, -7.51318583e-01,
          7.62990784e-01, -6.32961281e-01, -1.30244204e+00,
          6.85185568e-01,  2.30823161e-01, -3.55757279e-01],
        [ 1.51378870e+00,  9.17772031e-01,  1.03255776e+00,
          1.51841929e+00, -1.87016526e-01, -1.27343149e+00,
          1.30493570e+00, -2.80447012e+00,  1.46924110e-01,
          1.57111251e+00,  1.02932639e+00,  1.83625997e-01,
         -3.60972108e-01, -7.62725218e-01, -1.09225632e+00]],

       [[ 8.95953983e-01, -1.44198207e+00, -8.68512373e-01,
         -1.00658115e-01, -4.11748368e-01, -2.97652620e+00,
          2.36358093e+00, -1.64623471e+00,  1.45404386e+00,
          7.27599956e-02, -2.97921514e+00,  1.01342453e+00,
          8.58622973e-01,  1.63015505e+00,  1.36280977e+00],
        [ 1.84017147e+00, -1.88636397e+00, -1.83518464e+00,
         -2.28883541e-01, -9.687248

### Conversion between Einsum and @

---
It is surprisingly difficult, although extremely useful, to try to convert einsum to (generalized) matrix multiplication and back. The latter is much harder, albeit much more benificial due to the fact that eimsum can often be poorly optimized, resulting in performance degradation. 

Let us start by converting @ to einsums. 

In [ ]:
 x = np.random.randn(64, 10, 5)
 y = np.random.randn(5, 10)
 z_at = x @ y

Here is how we work out the exercise. 

1. Work out which dimension is broadcasted. In this case, $y$ has become $64 \times 5 \times 10$.
2. Work out the final dimension. In this case, it should be $64 \times 10 \times 10$. 
2. Work out how the matrix multiplication actually happens. In this case, it happens to the last trailing dimensions. 
3. Ignore the broadcast for a moment. Just write out the plain einsum for matrix mulitplication. `eimsum('ij, jk -> ik', x, y)`. 
4. Start from there and fill in the missing replicated part. **Be extremely careful about the dimensions that seem to be equal but are not.** In this case, there are two $10$ in the expression, but they are not **the same thing**!

In [ ]:
z_ein = np.einsum('bij, jk -> bik', x, y)
np.linalg.norm(z_at - z_ein) # They are not going to be exactly equal thanks for numerical errors. 

1.670343589058167e-14

To convert einsum to @ is much harder, and is not in general (easily) possible. 

There is no fixed routine to perform the tasks (since sometimes it is not even possible). However, it is very important to write out the sum and looks for the parts that looks like a matrix manipulation (if there is one). In general, $X = AB$ means $x_{ik} = \sum_j a_{ij}b_{jk}$. Therefore, once the latter occurs, just choose the dimension to conform to the matrix multiplication. When there are more summation in the einsum, it is better to stack the tensors along the dimensions so that there is only one sum. 

We will not delve too deep into the topics. Let us find the equivalent form of `np.einsum('ijk, jkh -> ijh', x, y)`.

1. Let us look write the expression $z_{ijh} = \sum_{k=1}^K x_{ijk} y_{jkh}$ as $z_{ijk} = x_{ij}^t y_{jh}$, where $x_{ij}$ and $y_{jh}$ are vectors. 
2. Now to get what we want, we have $\tilde{x}$ to be a $IJ \times K$ and $\tilde{y}$ to be a $K \times JH$ matrices. Now we can perform the matrix multiplication. 
3. The only problem is that we get a tensor that is essentially $I \times J \times J \times H$ and therefore somehow we get an additional $J$. The understand what this means, note that the general element we will have $x_{ij}^ty_{j'h}$, namely in the original situation we only compute things for $j = j'$ and when writing it out be matmul we have incur quite some heavy additional computations. 
4. To avoid the above overhead, the idea is to move $J$ to the broadcast dimension, that is we wnat a $J \times I \times K$ matrices and a $J \times K \times H$ matrices. You might have notice this solution quite early, but the reasoning shows that it is far from trivial to perform such tasks.                          

In [ ]:
I, J, K, H = 10, 15, 20, 25
x = np.random.randn(I, J, K)
y = np.random.randn(J, K, H)
z = np.einsum('ijk, jkh -> ijh', x, y)

z_bc = rearrange(rearrange(x, 'i j k -> j i k') @ y, 'j i h -> i j h')

In [ ]:
np.linalg.norm(z-z_bc)

3.8994031687856164e-14

## Sparse matrices
---
By default, numpy doesn't support sparse matrix operations. If one wishes to use sparse matrices, one must use `scipy.sparse`.

Sparse 'coo' format is basically a format that identify only the non-zero entries in a matrix. The following example should be self-explanatory.

In [ ]:
import numpy as np
from scipy.sparse import coo_matrix

row  = np.array([0, 3, 1, 0])
col  = np.array([0, 3, 1, 2])
data = np.array([4, 5, 7, 9])
coo_matrix((data, (row, col)), shape=(4, 4)).toarray()

array([[4, 0, 9, 0],
       [0, 7, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 5]])

In [ ]:
A = np.array([[1,2,0],[0,0,3],[1,0,4]])
coo_matrix(A)
print(coo_matrix(A).toarray())

[[1 2 0]
 [0 0 3]
 [1 0 4]]


In [ ]:
print(coo_matrix(A).dot(coo_matrix(A)))

  (0, 2)	6
  (0, 1)	2
  (0, 0)	1
  (1, 2)	12
  (1, 0)	3
  (2, 2)	16
  (2, 1)	2
  (2, 0)	5


## Jax

[Jax](https://github.com/google/jax) is a neural network libraries that looks like numpy, but supports jit, autograd etc with a functional programming style. 

In [ ]:
import jax 
import jax.numpy as jnp
from jax import random 
from jax import grad, jit, vmap
from jax import random

In [ ]:
key = random.PRNGKey(0)
x = random.normal(key, (10,))
print(x)

[-0.372111    0.26423106 -0.18252774 -0.7368198  -0.44030386 -0.15214427
 -0.6713536  -0.5908642   0.73168874  0.5673025 ]


One of the greatest advantage of the async operations and jit. Note that operations are async by default so one need to use block.

In [ ]:
def selu(x, alpha=1.67, lmbda=1.05):
    return lmbda * jnp.where(x > 0, x, alpha * jnp.exp(x) - alpha)

x = random.normal(key, (100000000,))
%timeit selu(x).block_until_ready()

The slowest run took 8.43 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 5: 612 ms per loop


To increase the speed, we invoke the `jit` command. 

In [ ]:
selu_jit = jit(selu)
%timeit selu_jit(x).block_until_ready()

The slowest run took 5.15 times longer than the fastest. This could mean that an intermediate result is being cached.
1 loop, best of 5: 124 ms per loop


A even better way is to specify recompilation for each alpha and lmbda

In [ ]:
@jax.partial(jax.jit, static_argnums=(1, 2,))
def selu(x, alpha=1.67, lmbda=1.05):
    return lmbda * jnp.where(x > 0, x, alpha * jnp.exp(x) - alpha)

%timeit selu(x, 1.67, 1.05).block_until_ready() # You cannot omit argument now.

10 loops, best of 5: 121 ms per loop


### vmap and pmap

`vmap` and `pmap` are two methods for apply parallel methods. 

In [ ]:
from jax import vmap, pmap

x = random.normal(key, (100000,100))

@jit 
def time_two(x):
    return x * 2.0

result_vmap = vmap(time_two, 0)(x).block_until_ready()

`pmap` can only be used for multiple xla devices (like mutiple gpu and cpu).

It is very important to consider the dot product case. According to the documentation, [this](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.dot_general.html#jax.lax.dot_general) is the signiture. It can be quite confusing. 

In [ ]:
from jax.lax import dot_general as dot
x = random.normal(key, (64,100, 10))
w = random.normal(key, (10, 15))

dot(x, w, (((2,),(0,)), ((),()))).shape

(64, 100, 15)

In [ ]:
from jax.lax import dot_general as dot
x = random.normal(key, (10, 64,100, 10))
w = random.normal(key, (10, 64,10, 15))

dot(x, w, (((3,),(2,)), ((0, 1,),(0, 1,)))).shape

(10, 64, 100, 15)

## Pandas and R

In short, pandas uses a syntax similar to that of R (dataframe) and will be our major 

### Pandas

This is basically the R dataframe in Pandas

In [ ]:
!git clone https://github.com/tolarteh/cardashians.git

Cloning into 'cardashians'...
remote: Enumerating objects: 64, done.
remote: Total 64 (delta 0), reused 0 (delta 0), pack-reused 64
Unpacking objects: 100% (64/64), done.


In [ ]:
import pandas as pd
import numpy as np

x_train = pd.read_csv('./cardashians/xtrain.csv', engine='python')
x_test = pd.read_csv('./cardashians/xtest.csv', engine='python')

y_train = pd.read_csv('./cardashians/ytrain.csv', engine='python')
y_test = pd.read_csv('./cardashians/ytest.csv', engine='python')

In [ ]:
TRAIN_IDX=x_train.shape[0]
TEST_IDX = TRAIN_IDX + x_test.shape[0]

In [ ]:
x = pd.concat([x_train, x_test], axis=0)
y = pd.concat([y_train, y_test], axis=0)

data = pd.concat([x, y], axis=1)

In [ ]:
data.columns.to_list()

['VehicleAge',
 'VehOdo',
 'MMRAcquisitionAuctionAveragePrice',
 'MMRAcquisitionAuctionCleanPrice',
 'MMRAcquisitionRetailAveragePrice',
 'MMRAcquisitonRetailCleanPrice',
 'MMRCurrentAuctionAveragePrice',
 'MMRCurrentAuctionCleanPrice',
 'MMRCurrentRetailAveragePrice',
 'MMRCurrentRetailCleanPrice',
 'BYRNO',
 'VehBCost',
 'IsOnlineSale',
 'WarrantyCost',
 'Auction_ADESA',
 'Auction_MANHEIM',
 'Auction_OTHER',
 'Make_ACURA',
 'Make_BUICK',
 'Make_CADILLAC',
 'Make_CHEVROLET',
 'Make_CHRYSLER',
 'Make_DODGE',
 'Make_FORD',
 'Make_GMC',
 'Make_HONDA',
 'Make_HUMMER',
 'Make_HYUNDAI',
 'Make_INFINITI',
 'Make_ISUZU',
 'Make_JEEP',
 'Make_KIA',
 'Make_LEXUS',
 'Make_LINCOLN',
 'Make_MAZDA',
 'Make_MERCURY',
 'Make_MINI',
 'Make_MITSUBISHI',
 'Make_NISSAN',
 'Make_OLDSMOBILE',
 'Make_PLYMOUTH',
 'Make_PONTIAC',
 'Make_SATURN',
 'Make_SCION',
 'Make_SUBARU',
 'Make_SUZUKI',
 'Make_TOYOTA',
 'Make_TOYOTA SCION',
 'Make_VOLKSWAGEN',
 'Make_VOLVO',
 'Color_BEIGE',
 'Color_BLACK',
 'Color_BLUE',

In [ ]:
data['IsBadBuy'].unique()

array([0, 1])

In [ ]:
data['IsBadBuy'].value_counts()

0    64007
1     8976
Name: IsBadBuy, dtype: int64

Both of the following methods are ok. However, the latter one if preferred.

In [ ]:
data['VehicleAge'][data['VehicleAge']>3].count()
data.loc[data['VehicleAge']>3, 'VehicleAge'].count()

45503

In [ ]:
data.loc[(data['VehOdo'] > 5000)&(data['VehicleAge']>3), ['VehOdo', 'VehicleAge']]

VehOdo  VehicleAge
1       84095           4
3       73746           6
4       81897           7
8       76429           7
10      73260           6
...       ...         ...
14589   72266           6
14590   76158           5
14591   84025           5
14595   54282           5
14596   79306           6

[45503 rows x 2 columns]

In [ ]:
data[data.VehOdo.between(1000,20000)] # This is also possible

VehicleAge  VehOdo  ...  VNST_WV  IsBadBuy
147             2   12628  ...        0         0
2876            1   13445  ...        0         1
6111            1   19610  ...        0         1
7564            4   14547  ...        0         0
7977            1   10643  ...        0         0
11084           5   17538  ...        0         0
12094           6   15655  ...        0         0
13092           2   10095  ...        0         1
14246           8   19070  ...        0         0
17491           6    5368  ...        0         0
19000           5   19430  ...        0         0
20035           3   15894  ...        0         0
27551           3   15249  ...        0         0
28299           5   14187  ...        0         0
36221           7   18440  ...        0         0
36699           3   16545  ...        0         1
40461           2   18813  ...        0         0
42083           1    9446  ...        0         1
42734           4    9878  ...        0         0
45365           2   19751  ...        0         0
45583           2   18923  ...        0         0
46703           5   14474  ...        0         0
46803           1   17502  ...        0         1
48345           5   19200  ...        0         0
49287           5   18777  ...        0         0
49610           2   12926  ...        0         0
50021           2   11662  ...        0         1
50367           3   15409  ...        0         1
51978           2   15743  ...        0         1
53834           2   13924  ...        0         1
53979           5   19825  ...        0         0
55574           5   16574  ...        0         0
55789           7   19983  ...        0         0
57292           6   19534  ...        0         0
58356           1    8706  ...        0         0
3697            1   19137  ...        0         0
4050            7   14961  ...        0         1
4171            5   16713  ...        0         0
5837            6   17281  ...        0         0
9783            6   14519  ...        0         0
12712           5   19813  ...        0         0
14197           2   16833  ...        0         0
14216           3    4825  ...        0         1

[43 rows x 145 columns]

In [ ]:
data.iloc[0:100, 0:2]

VehicleAge  VehOdo
0            2   75645
1            4   84095
2            3   51780
3            6   73746
4            7   81897
..         ...     ...
95           4   88650
96           8   86059
97           9   82417
98           8   86206
99           3   60225

[100 rows x 2 columns]

Using maps for pandas.

In [ ]:
data.iloc[:, 0].map(lambda x: 0 if x > 10 else 1)
data.iloc[:, 0].apply(lambda x: 0 if x > 10 else 1)

0        1
1        1
2        1
3        1
4        1
        ..
14592    1
14593    1
14594    1
14595    1
14596    1
Name: VehicleAge, Length: 72983, dtype: int64

Groupby in Pandas

In [ ]:
aggregated = data[['VehicleAge', 'IsBadBuy']].groupby('IsBadBuy', as_index=False).agg('mean')

In [ ]:
merge = data.merge(aggregated, how='left', on='IsBadBuy')

### Some additional cool functionality of pandas

In [ ]:
!pip install pandasql

In [ ]:
from pandasql import sqldf


In [ ]:
pysqldf = lambda q: sqldf(q, globals())

In [ ]:
q = """SELECT VehicleAge
       FROM data 
       LIMIT 10;"""

names = pysqldf(q)
names

OperationalError: ignored

We can also use some very nice describe function

In [ ]:
data.VehicleAge.describe()

count    72983.000000
mean         4.176644
std          1.712210
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          9.000000
Name: VehicleAge, dtype: float64

In [ ]:
data.VehicleAge.describe(percentiles=np.arange(0, 1, 0.1))

count    72983.000000
mean         4.176644
std          1.712210
min          0.000000
0%           0.000000
10%          2.000000
20%          3.000000
30%          3.000000
40%          4.000000
50%          4.000000
60%          4.000000
70%          5.000000
80%          6.000000
90%          7.000000
max          9.000000
Name: VehicleAge, dtype: float64

In [ ]:
data.groupby('IsBadBuy').describe(percentiles=np.arange(0, 1, 0.1))

VehicleAge                                ... VNST_WV                    
              count      mean       std  min   0%  ...     60%  70%  80%  90%  max
IsBadBuy                                           ...                            
0           64007.0  4.069461  1.677024  0.0  0.0  ...     0.0  0.0  0.0  0.0  1.0
1            8976.0  4.940954  1.765302  1.0  1.0  ...     0.0  0.0  0.0  0.0  1.0

[2 rows x 2160 columns]

### R and dplyr

dplyr is yet another package to simplify EDA. There are tons of available routines, see [here](https://dplyr.tidyverse.org/reference/index.html).

In [ ]:
%load_ext rpy2.ipython

In [ ]:
%%R
install.packages("dplyr")

In [ ]:
%%R
library('dplyr')


In [ ]:
%%R

colnames(starwars)

In [ ]:
%%R 

starwars %>% filter(height >= 5) %>% 
         select(name, ends_with('color')) 

In [ ]:
%%R

starwars %>% 
  mutate(name, bmi = mass / ((height / 100)  ^ 2)) %>%
  select(name:mass, bmi)



In [ ]:
%%R

starwars %>% 
  arrange(desc(mass))

In [ ]:
%%R

starwars %>%
  group_by(species) %>%
  summarise(
    n = n(),
    mass = mean(mass, na.rm = TRUE)
  ) %>%
  filter(
    n > 1,
    mass > 50
  )

## Matplotlib and Tensorboard
---

### Matplotlib
---
Let us use `matplotlib` to draw some commonly used graphs, such as Line Chart, scatter plots, histograms, box plots,

In [ ]:
!pip install matplotlib

#### Line Chart

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x_axis = [1, 2, 3, 4]
y_axis = [1, 4, 9, 16]
plt.plot(x_axis,y_axis)
plt.show()

#### Scatter Plot


In [ ]:
x_axis = [1, 2, 3, 4]
y_axis = [1, 4, 9, 16]
plt.scatter(x_axis,y_axis)
plt.show()

#### Histograms

In [ ]:
x_axis = ['group_a', 'group_b', 'group_c']
y_axis = [1, 10, 100]

plt.bar(x_axis, y_axis)
plt.show()


 Boxplot

In [ ]:
#make there Normalize arrays
datas = [np.random.normal(0,std,100) for std in range(1,4)]

plt.boxplot(datas) 
plt.show()

So far, we have simply drawn the pictures, but their display effect is not good

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

x_axis = [1, 2, 3, 4]
y_axis = [1, 4, 9, 16]

plt.plot(x_axis,y_axis,color="r") # change the color by color param
plt.xlabel("X_label") # add x axis title
plt.ylabel("Y_lable") # add y axis title
plt.title("line_chart") # add picture title
plt.show()

draw different line in one chart.

In [ ]:
# make the data
t = np.arange(0., 5., 0.2)

# draw three different with red dashes, blue squares and green triangles
plt.plot(t, t, 'r--', t, t**2, 'bs', t, t**3, 'g^')
plt.show()

draw four sub chart in one chart

In [ ]:
t=np.arange(0.0,2.0,0.1)
s=np.sin(t*np.pi)
# draw 2 X 2 subplot, plt.subplot(row,column,row), this is the first chart
plt.subplot(2,2,1)
plt.title('chart 1')
plt.plot(t,s,'b--')

# this is the second chart
plt.subplot(2,2,2) 
plt.title('chart 2')
plt.plot(2*t,s,'r--')

# this is the third chart
plt.subplot(2,2,3)
plt.title('chart 3')
plt.plot(3*t,s,'m--')

# this is the fourth chart
plt.subplot(2,2,4)
plt.title('chart 4')
plt.plot(4*t,s,'k--')

plt.show()


### Tensorboard

In [ ]:
! pip install tensorboardX crc32c soundfile

In [ ]:
%load_ext tensorboard

In [ ]:
from datetime import datetime
from packaging import version

import tensorflow as tf
from tensorflow import keras

import numpy as np

using a simple regression to show how does tensorboard work

In [ ]:
data_size = 1000
train_data_percent = 0.8
train_size = int(data_size * train_data_percent)
# create input data between -1 and 1 and randomize it.
x = np.linspace(-1, 1, data_size)
np.random.shuffle(x)

# Generate the output data.
# y = 0.5x + 1 + noise
y = 0.5 * x + 1 + np.random.normal(0, 0.05, (data_size, ))

# Split into test and train pairs.
x_train, y_train = x[:train_size], y[:train_size]
x_test, y_test = x[train_size:], y[train_size:]

In [ ]:
! rm -rf logs/scalars

start model traning

In [ ]:
logdir = "logs/scalars/" + datetime.now().strftime("%Y%m%d-%H%M%S")
file_writer = tf.summary.create_file_writer(logdir + "/metrics")
file_writer.set_as_default()

def lr_schedule(epoch):
  """
  Returns a custom learning rate that decreases as epochs progress.
  """
  learning_rate = 0.2
  if epoch > 10:
    learning_rate = 0.1
  if epoch > 20:
    learning_rate = 0.05
  if epoch > 50:
    learning_rate = 0.01

  tf.summary.scalar('learning rate', data=learning_rate, step=epoch)
  return learning_rate

lr_callback = keras.callbacks.LearningRateScheduler(lr_schedule)
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

model = keras.models.Sequential([
    keras.layers.Dense(16, input_dim=1),
    keras.layers.Dense(1),
])

model.compile(
    loss='mse', # keras.losses.mean_squared_error
    optimizer=keras.optimizers.SGD(),
)

training_history = model.fit(
    x_train, # input
    y_train, # output
    batch_size=train_size,
    verbose=0, # Suppress chatty output; use Tensorboard instead
    epochs=100,
    validation_data=(x_test, y_test),
    callbacks=[tensorboard_callback, lr_callback],
)

In [ ]:
%tensorboard --logdir logs/scalars